Wp/21/1
andrey-sikerin/todo_list_app_sirius pull request #34
Opened 2021-12-12 22:41 UTC by Artem-Goldenberg

Added AddNewTaskCell to the end of the TableView

2021-12-13 15:21 UTC, andrey-sikerin requested changes

2021-12-13 15:21 UTC, andrey-sikerin commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    private struct PlusIcon {
PlusIconLayoutStyle?

2021-12-13 15:21 UTC, andrey-sikerin commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    private struct Label {
предложу завести структуру и объявить в экстешене static let?

2021-12-13 15:21 UTC, andrey-sikerin commented on TODO_list_app/TaskListViewController.swift
> +    private static let numberOfRows = 20
предложу объявить приватную локальную пееременну

2021-12-13 15:21 UTC, andrey-sikerin commented on TODO_list_app/TaskListViewController.swift
> +//        guard let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath) as? ToDoCell else { return UITableViewCell() }
коментаренный код никогда не льем

2021-12-13 17:08 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
> +//        guard let cell = tableView.dequeueReusableCell(withIdentifier: reuseIdentifier, for: indexPath) as? ToDoCell else { return UITableViewCell() }
Удалил

2021-12-13 17:08 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
> +    private static let numberOfRows = 20
Вынес в локальную

2021-12-13 17:09 UTC, Artem-Goldenberg commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    private struct PlusIcon {
Переименовал

2021-12-14 11:52 UTC, andrey-sikerin requested changes

2021-12-14 11:52 UTC, andrey-sikerin commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    static let cellHeight: CGFloat = 56
эта переменная нужна?, ниже у тебя есть переменна defaultHeight?

2021-12-14 11:52 UTC, andrey-sikerin commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    init(plusIconLayoutStyle: PlusIconLayoutStyle = .defaultStyle, labelStyle: LabelStyle = .defaultStyle) {
предложу выровнять столбиков по одной переменной на строчку

2021-12-14 11:52 UTC, andrey-sikerin commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +        super.init(style: .default, reuseIdentifier: nil)
нужно задавать для ячейки reuseIdentifier

2021-12-14 11:52 UTC, andrey-sikerin commented on TODO_list_app/TaskListViewController.swift
>          tableView.register(UITableViewCell.self, forCellReuseIdentifier: reuseIdentifier)
здесь нужно регистрировать конкретные типы ячеек AddNewTaskCell

2021-12-14 11:52 UTC, andrey-sikerin commented on TODO_list_app/TaskListViewController.swift
> +            let newTaskCell = AddNewTaskCell()
ты создаешь ячейку каждый раз а нужно просить ее из UITableView через метод https://developer.apple.com/documentation/uikit/uitableview/1614891-dequeuereusablecell

2021-12-14 11:54 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
> +private lazy var plusButton: UIButton = {
Сделал

2021-12-14 11:56 UTC, Artem-Goldenberg commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    init(plusIconLayoutStyle: PlusIconLayoutStyle = .defaultStyle, labelStyle: LabelStyle = .defaultStyle) {
Сделал

2021-12-14 11:58 UTC, Artem-Goldenberg commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +        super.init(style: .default, reuseIdentifier: nil)
Задал

2021-12-14 12:02 UTC, Artem-Goldenberg commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    static let cellHeight: CGFloat = 56
Ну в TaskViewController defaultHeight это для TodoCell ячеек, а это индивидуально для моей ячейки, вдруг размер остальных ячеек измениться а мне нужно именно 56

2021-12-14 12:05 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
>          tableView.register(UITableViewCell.self, forCellReuseIdentifier: reuseIdentifier)
Это из-за того что у меня нет TodoCell ячейки пока, она появиться в следующих комитах

2021-12-14 12:07 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
> +            let newTaskCell = AddNewTaskCell()
Сделал

2021-12-14 12:09 UTC, Artem-Goldenberg commented on TODO_list_app/Cells/AddNewTaskCell.swift
> +    static let cellHeight: CGFloat = 56
Исправил

2021-12-14 12:10 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
>          tableView.register(UITableViewCell.self, forCellReuseIdentifier: reuseIdentifier)
Сделал

2021-12-14 12:24 UTC, andrey-sikerin requested changes

2021-12-14 12:24 UTC, andrey-sikerin commented on TODO_list_app/TaskListViewController.swift
> +        print("Cell dequeued")
код нужно лить без print

2021-12-14 12:28 UTC, Artem-Goldenberg commented on TODO_list_app/TaskListViewController.swift
> +        print("Cell dequeued")
убрал

2021-12-14 12:36 UTC, merged