Calendar Works
andrey-sikerin/todo_list_app_sirius pull request #59
Opened 2021-12-15 11:23 UTC by Artem-Goldenberg

2021-12-15 11:50 UTC, andrey-sikerin requested changes

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/Graphs/RootGraph.swift
> +        rootViewController = UINavigationController(rootViewController: editTaskViewController)
этот код нужен или его нужно закоментарить?

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/Graphs/RootGraph.swift
> +        rootViewController = UINavigationController(rootViewController: editTaskViewController)
может его уже удалим?

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +//    private func setItemsLayout() {
коментаренный код - он нужен?

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // Stack View
такие коменты не пишем - предожу убрать

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // Set deadLineStackView
такие комменты не пишем - предложу убрать

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // calculates height of smallStackViews
такие коменты не пишем - обычно структура коммента TODO(nickname): fix me in [номер тикета]

2021-12-15 11:50 UTC, andrey-sikerin commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        view.addGestureRecognizer(gestureRecognizer) // not working with this
что означает коммент?

2021-12-15 12:49 UTC, Artem-Goldenberg commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // Set deadLineStackView
Убрал

2021-12-15 12:49 UTC, Artem-Goldenberg commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // calculates height of smallStackViews
Убрал

2021-12-15 12:50 UTC, Artem-Goldenberg commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        view.addGestureRecognizer(gestureRecognizer) // not working with this
Это старая проблема, уже решил, убрал

2021-12-15 12:54 UTC, Artem-Goldenberg commented on TODO_list_app/ViewControllers/EditTaskViewController.swift
> +        // Stack View
убрал

2021-12-16 08:08 UTC, andrey-sikerin approved these changes

2021-12-16 08:14 UTC, merged